"""add password credentials

Revision ID: 07b6bb28ab24
Revises: 95ab5b81e296
Create Date: 2026-08-16 04:47:39.977243

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "07b6bb28ab24"
down_revision: Union[str, None] = "95ab5b81e296"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_credentials",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "password_changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "user_id"],
            ["users.tenant_id", "users.id"],
            name="fk_password_credentials_tenant_user_users",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_password_credentials_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_credentials")),
        sa.UniqueConstraint(
            "tenant_id", "user_id", name="uq_password_credentials_tenant_id_user_id"
        ),
    )
    op.create_index(
        op.f("ix_password_credentials_tenant_id"),
        "password_credentials",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_credentials_user_id"), "password_credentials", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_password_credentials_user_id"), table_name="password_credentials")
    op.drop_index(op.f("ix_password_credentials_tenant_id"), table_name="password_credentials")
    op.drop_table("password_credentials")
    # ### end Alembic commands ###
